-- ============================================================================
-- Tibia Party Manager — tabela de referência boss -> item (loot table)
-- ============================================================================
-- Pedido do usuário em 2026-08-14: migrar BOSS_ITEMS
-- (services/lootdrop/boss-items-data.ts) pro banco, no mesmo espírito de
-- boss_quests (migration 20260814040000). Antes, BOSS_ITEMS misturava
-- granularidade (chaves de quest com vários bosses E chaves de boss
-- individual) e o dropdown de Item no DropFormModal resolvia isso na hora
-- (resolveItemsForBoss: boss direto, senão quest do boss). Agora cada boss
-- individual (os 26 de boss_quests) tem sua própria lista de itens de
-- verdade na tabela, sem heurística de fallback no client.
--
-- Correção de dado explícita do usuário nesta migração: os itens "Grand
-- Sanguine *" apareciam pra qualquer um dos 5 bosses de Rotten Blood
-- (Chagorz, Vemiath, Ichgahal, Murcion, Bakra), mas só caem do Bakra. Os
-- outros 24 itens de Rotten Blood (8 diversos + 16 "Sanguine *" sem
-- "Grand") continuam nos 5 bosses, sem mudança — só os Grand Sanguine
-- foram restringidos.
--
-- Todo o resto foi migrado 1:1 com o comportamento anterior de
-- resolveItemsForBoss (sem inventar nenhuma outra restrição por boss que o
-- usuário não pediu): bosses que já eram chave direta em BOSS_ITEMS
-- (SoulCore, Warzone, Vladrukh, Arbaziloth, The Rootkraken, Phosphorus, os 5
-- de Grave Borne, Crypt) mantêm exatamente os mesmos itens; bosses que só
-- existiam via fallback de quest (os 5 de Rotten Blood, os 6 de Soul War,
-- Plunder, Maior Domus, Mima Haffar) recebem o pool inteiro da quest —
-- Phosphorus, apesar de estar em "Make Belive" na tabela boss_quests, NUNCA
-- usava o pool de "Make Belive" (tinha entrada própria com prioridade), e
-- continua assim aqui.
--
-- Dado universal do jogo (não é por conta/party) — sem account_id, mesmo
-- padrão de xp_levels/boss_quests: RLS ligada só pra bloquear escrita via
-- client, leitura pública. FK pra boss_quests(boss) garante que todo boss
-- aqui já está cadastrado lá.
-- ============================================================================

create table if not exists boss_items (
  boss text not null references boss_quests(boss) on delete cascade,
  item text not null,
  primary key (boss, item)
);

comment on table boss_items is 'Loot table por boss individual (o que cada boss dropa) — substitui BOSS_ITEMS (services/lootdrop/boss-items-data.ts), que continua no repo só como fonte de nomes de item pro script fetch-item-icons.mjs, não é mais usado pro dropdown de Item no formulário de drop.';

create index if not exists idx_boss_items_boss on boss_items(boss);

alter table boss_items enable row level security;

create policy "public_read_boss_items" on boss_items
  for select
  to anon, authenticated
  using (true);

insert into boss_items (boss, item) values
  ('SoulCore', 'SoulCore Sulphur Spouter'),
  ('SoulCore', 'SoulCore Sulphider'),
  ('SoulCore', 'SoulCore Undertaker'),
  ('SoulCore', 'SoulCore Nighthunter'),
  ('SoulCore', 'SoulCore Stalking Stalk'),
  ('SoulCore', 'SoulCore Darklight Constructor'),
  ('SoulCore', 'SoulCore Darklight Emitter'),
  ('SoulCore', 'SoulCore Wandering Pillar'),
  ('SoulCore', 'SoulCore Darklight Source'),
  ('SoulCore', 'SoulCore Darklight Striker'),
  ('SoulCore', 'SoulCore Darklight Matter'),
  ('SoulCore', 'SoulCore Walking Pillar'),
  ('SoulCore', 'SoulCore Mycobiontic Beetle'),
  ('SoulCore', 'SoulCore Bloated Man-maggot'),
  ('SoulCore', 'SoulCore Oozing Corpus'),
  ('SoulCore', 'SoulCore Sopping Corpus'),
  ('SoulCore', 'SoulCore Meandering Mushroom'),
  ('SoulCore', 'SoulCore Rotten Man-maggot'),
  ('SoulCore', 'SoulCore Oozing Carcass'),
  ('SoulCore', 'SoulCore Sopping Carcass'),
  ('Warzone', 'Gnome Legs'),
  ('Warzone', 'Gnome Armor'),
  ('Warzone', 'Gnome Helmet'),
  ('Vladrukh', 'Norcferatu Bloodhide'),
  ('Vladrukh', 'Norcferatu Bonecloak'),
  ('Vladrukh', 'Norcferatu Tuskplate'),
  ('Vladrukh', 'Norcferatu Fangstompers'),
  ('Vladrukh', 'Norcferatu Goretrampers'),
  ('Vladrukh', 'Norcferatu Bloodstrider'),
  ('Vladrukh', 'Norcferatu Fleshguards'),
  ('Vladrukh', 'Norcferatu Thornwraps'),
  ('Vladrukh', 'Norcferatu Bonehood'),
  ('Vladrukh', 'Norcferatu Skullguard'),
  ('Eldritch Dragon Lord', 'Fiery Crypt Rune'),
  ('Ice Horror', 'Icy Crypt Rune'),
  ('The Gravedigger', 'Deathly Crypt Rune'),
  ('Adventurer Group', 'Ancient Crypt Rune'),
  ('Bone Overlord', 'Necromantic Crypt Rune'),
  ('Crypt', 'Crypt Spine'),
  ('Crypt', 'Crypt Slicer'),
  ('Crypt', 'Crypt Bile'),
  ('Crypt', 'Crypt Strike'),
  ('Crypt', 'Crypt Splitter'),
  ('Crypt', 'Crypt Breaker'),
  ('Crypt', 'Crypt Jaw'),
  ('Arbaziloth', 'Demon Claws'),
  ('Arbaziloth', 'Demon Skull'),
  ('Arbaziloth', 'Demon In A Green Box'),
  ('Arbaziloth', 'Inferniarch Arbalest'),
  ('Arbaziloth', 'Inferniarch Battleaxe'),
  ('Arbaziloth', 'Inferniarch Blade'),
  ('Arbaziloth', 'Inferniarch Bow'),
  ('Arbaziloth', 'Inferniarch Claws'),
  ('Arbaziloth', 'Inferniarch Flail'),
  ('Arbaziloth', 'Inferniarch Greataxe'),
  ('Arbaziloth', 'Inferniarch Rod'),
  ('Arbaziloth', 'Inferniarch Slayer'),
  ('Arbaziloth', 'Inferniarch Wand'),
  ('Arbaziloth', 'Inferniarch Warhammer'),
  ('Arbaziloth', 'Maliceforged Helmet'),
  ('Arbaziloth', 'Hellstalker Visor'),
  ('Arbaziloth', 'Dreadfire Headpiece'),
  ('Arbaziloth', 'Demonfang Mask'),
  ('Arbaziloth', 'Demon Mengu'),
  ('The Rootkraken', 'Amber Bow'),
  ('The Rootkraken', 'Amber Crossbow'),
  ('The Rootkraken', 'Amber Cudgel'),
  ('The Rootkraken', 'Amber Bludgeon'),
  ('The Rootkraken', 'Amber Axe'),
  ('The Rootkraken', 'Amber Greataxe'),
  ('The Rootkraken', 'Amber Slayer'),
  ('The Rootkraken', 'Amber Sabre'),
  ('The Rootkraken', 'Amber Rod'),
  ('The Rootkraken', 'Amber Wand'),
  ('The Rootkraken', 'Amber Kusarigama'),
  ('The Rootkraken', 'Strange Inedible Fruit'),
  ('Phosphorus', 'Auric Moon Sigil'),
  ('Phosphorus', 'Cloud in a Bottle'),
  ('Phosphorus', 'Moonsilver Axe'),
  ('Phosphorus', 'Moonsilver Bow'),
  ('Phosphorus', 'Moonsilver Channeler'),
  ('Phosphorus', 'Moonsilver Chopper'),
  ('Phosphorus', 'Moonsilver Claymore'),
  ('Phosphorus', 'Moonsilver Crusher'),
  ('Phosphorus', 'Moonsilver Crossbow'),
  ('Phosphorus', 'Moonsilver Epee'),
  ('Phosphorus', 'Moonsilver Katar'),
  ('Phosphorus', 'Moonsilver Mace'),
  ('Phosphorus', 'Moonsilver Sceptre'),
  ('Bakra', 'Grand Sanguine Battleaxe'),
  ('Bakra', 'Grand Sanguine Blade'),
  ('Bakra', 'Grand Sanguine Bludgeon'),
  ('Bakra', 'Grand Sanguine Bow'),
  ('Bakra', 'Grand Sanguine Coil'),
  ('Bakra', 'Grand Sanguine Crossbow'),
  ('Bakra', 'Grand Sanguine Cudgel'),
  ('Bakra', 'Grand Sanguine Hatchet'),
  ('Bakra', 'Grand Sanguine Razor'),
  ('Bakra', 'Grand Sanguine Rod'),
  ('Bakra', 'Grand Sanguine Claws'),
  ('Chagorz', 'Abridged Promotion Scroll'),
  ('Chagorz', 'Advanced Promotion Scroll'),
  ('Chagorz', 'Basic Promotion Scroll'),
  ('Chagorz', 'Spiritual Horseshoes'),
  ('Chagorz', 'Cursed Wood'),
  ('Chagorz', 'Darklight Geode'),
  ('Chagorz', 'darklight heart'),
  ('Chagorz', 'Tainted Heart'),
  ('Chagorz', 'Sanguine Battleaxe'),
  ('Chagorz', 'Sanguine Blade'),
  ('Chagorz', 'Sanguine Bludgeon'),
  ('Chagorz', 'Sanguine Boots'),
  ('Chagorz', 'Sanguine Bow'),
  ('Chagorz', 'Sanguine Coil'),
  ('Chagorz', 'Sanguine Crossbow'),
  ('Chagorz', 'Sanguine Cudgel'),
  ('Chagorz', 'Sanguine Galoshes'),
  ('Chagorz', 'Sanguine Greaves'),
  ('Chagorz', 'Sanguine Hatchet'),
  ('Chagorz', 'Sanguine Legs'),
  ('Chagorz', 'Sanguine Razor'),
  ('Chagorz', 'Sanguine Rod'),
  ('Chagorz', 'Sanguine Trousers'),
  ('Chagorz', 'Sanguine Claws'),
  ('Vemiath', 'Abridged Promotion Scroll'),
  ('Vemiath', 'Advanced Promotion Scroll'),
  ('Vemiath', 'Basic Promotion Scroll'),
  ('Vemiath', 'Spiritual Horseshoes'),
  ('Vemiath', 'Cursed Wood'),
  ('Vemiath', 'Darklight Geode'),
  ('Vemiath', 'darklight heart'),
  ('Vemiath', 'Tainted Heart'),
  ('Vemiath', 'Sanguine Battleaxe'),
  ('Vemiath', 'Sanguine Blade'),
  ('Vemiath', 'Sanguine Bludgeon'),
  ('Vemiath', 'Sanguine Boots'),
  ('Vemiath', 'Sanguine Bow'),
  ('Vemiath', 'Sanguine Coil'),
  ('Vemiath', 'Sanguine Crossbow'),
  ('Vemiath', 'Sanguine Cudgel'),
  ('Vemiath', 'Sanguine Galoshes'),
  ('Vemiath', 'Sanguine Greaves'),
  ('Vemiath', 'Sanguine Hatchet'),
  ('Vemiath', 'Sanguine Legs'),
  ('Vemiath', 'Sanguine Razor'),
  ('Vemiath', 'Sanguine Rod'),
  ('Vemiath', 'Sanguine Trousers'),
  ('Vemiath', 'Sanguine Claws'),
  ('Ichgahal', 'Abridged Promotion Scroll'),
  ('Ichgahal', 'Advanced Promotion Scroll'),
  ('Ichgahal', 'Basic Promotion Scroll'),
  ('Ichgahal', 'Spiritual Horseshoes'),
  ('Ichgahal', 'Cursed Wood'),
  ('Ichgahal', 'Darklight Geode'),
  ('Ichgahal', 'darklight heart'),
  ('Ichgahal', 'Tainted Heart'),
  ('Ichgahal', 'Sanguine Battleaxe'),
  ('Ichgahal', 'Sanguine Blade'),
  ('Ichgahal', 'Sanguine Bludgeon'),
  ('Ichgahal', 'Sanguine Boots'),
  ('Ichgahal', 'Sanguine Bow'),
  ('Ichgahal', 'Sanguine Coil'),
  ('Ichgahal', 'Sanguine Crossbow'),
  ('Ichgahal', 'Sanguine Cudgel'),
  ('Ichgahal', 'Sanguine Galoshes'),
  ('Ichgahal', 'Sanguine Greaves'),
  ('Ichgahal', 'Sanguine Hatchet'),
  ('Ichgahal', 'Sanguine Legs'),
  ('Ichgahal', 'Sanguine Razor'),
  ('Ichgahal', 'Sanguine Rod'),
  ('Ichgahal', 'Sanguine Trousers'),
  ('Ichgahal', 'Sanguine Claws'),
  ('Murcion', 'Abridged Promotion Scroll'),
  ('Murcion', 'Advanced Promotion Scroll'),
  ('Murcion', 'Basic Promotion Scroll'),
  ('Murcion', 'Spiritual Horseshoes'),
  ('Murcion', 'Cursed Wood'),
  ('Murcion', 'Darklight Geode'),
  ('Murcion', 'darklight heart'),
  ('Murcion', 'Tainted Heart'),
  ('Murcion', 'Sanguine Battleaxe'),
  ('Murcion', 'Sanguine Blade'),
  ('Murcion', 'Sanguine Bludgeon'),
  ('Murcion', 'Sanguine Boots'),
  ('Murcion', 'Sanguine Bow'),
  ('Murcion', 'Sanguine Coil'),
  ('Murcion', 'Sanguine Crossbow'),
  ('Murcion', 'Sanguine Cudgel'),
  ('Murcion', 'Sanguine Galoshes'),
  ('Murcion', 'Sanguine Greaves'),
  ('Murcion', 'Sanguine Hatchet'),
  ('Murcion', 'Sanguine Legs'),
  ('Murcion', 'Sanguine Razor'),
  ('Murcion', 'Sanguine Rod'),
  ('Murcion', 'Sanguine Trousers'),
  ('Murcion', 'Sanguine Claws'),
  ('Bakra', 'Abridged Promotion Scroll'),
  ('Bakra', 'Advanced Promotion Scroll'),
  ('Bakra', 'Basic Promotion Scroll'),
  ('Bakra', 'Spiritual Horseshoes'),
  ('Bakra', 'Cursed Wood'),
  ('Bakra', 'Darklight Geode'),
  ('Bakra', 'darklight heart'),
  ('Bakra', 'Tainted Heart'),
  ('Bakra', 'Sanguine Battleaxe'),
  ('Bakra', 'Sanguine Blade'),
  ('Bakra', 'Sanguine Bludgeon'),
  ('Bakra', 'Sanguine Boots'),
  ('Bakra', 'Sanguine Bow'),
  ('Bakra', 'Sanguine Coil'),
  ('Bakra', 'Sanguine Crossbow'),
  ('Bakra', 'Sanguine Cudgel'),
  ('Bakra', 'Sanguine Galoshes'),
  ('Bakra', 'Sanguine Greaves'),
  ('Bakra', 'Sanguine Hatchet'),
  ('Bakra', 'Sanguine Legs'),
  ('Bakra', 'Sanguine Razor'),
  ('Bakra', 'Sanguine Rod'),
  ('Bakra', 'Sanguine Trousers'),
  ('Bakra', 'Sanguine Claws'),
  ('Malice', 'Spectral Horseshoes'),
  ('Malice', 'Spectral Horse Tack'),
  ('Malice', 'Spectral Saddle'),
  ('Malice', 'The Skull of a Beast'),
  ('Malice', 'Bracelet of Strengthening'),
  ('Malice', 'Pair of Soulstalkers'),
  ('Malice', 'Pair of Soulwalkers'),
  ('Malice', 'Soulbastion'),
  ('Malice', 'Soulbiter'),
  ('Malice', 'Soulbleeder'),
  ('Malice', 'Soulcrusher'),
  ('Malice', 'Soulcutter'),
  ('Malice', 'Souleater (Axe)'),
  ('Malice', 'Soulhexer'),
  ('Malice', 'Soulmaimer'),
  ('Malice', 'Soulmantle'),
  ('Malice', 'Soulpiercer'),
  ('Malice', 'Soulshanks'),
  ('Malice', 'Soulshell'),
  ('Malice', 'Soulshredder'),
  ('Malice', 'Soulshroud'),
  ('Malice', 'Soulstrider'),
  ('Malice', 'Soultainter'),
  ('Malice', 'Soulgarb'),
  ('Malice', 'Soulsoles'),
  ('Malice', 'Soulkamas'),
  ('Greed', 'Spectral Horseshoes'),
  ('Greed', 'Spectral Horse Tack'),
  ('Greed', 'Spectral Saddle'),
  ('Greed', 'The Skull of a Beast'),
  ('Greed', 'Bracelet of Strengthening'),
  ('Greed', 'Pair of Soulstalkers'),
  ('Greed', 'Pair of Soulwalkers'),
  ('Greed', 'Soulbastion'),
  ('Greed', 'Soulbiter'),
  ('Greed', 'Soulbleeder'),
  ('Greed', 'Soulcrusher'),
  ('Greed', 'Soulcutter'),
  ('Greed', 'Souleater (Axe)'),
  ('Greed', 'Soulhexer'),
  ('Greed', 'Soulmaimer'),
  ('Greed', 'Soulmantle'),
  ('Greed', 'Soulpiercer'),
  ('Greed', 'Soulshanks'),
  ('Greed', 'Soulshell'),
  ('Greed', 'Soulshredder'),
  ('Greed', 'Soulshroud'),
  ('Greed', 'Soulstrider'),
  ('Greed', 'Soultainter'),
  ('Greed', 'Soulgarb'),
  ('Greed', 'Soulsoles'),
  ('Greed', 'Soulkamas'),
  ('Spite', 'Spectral Horseshoes'),
  ('Spite', 'Spectral Horse Tack'),
  ('Spite', 'Spectral Saddle'),
  ('Spite', 'The Skull of a Beast'),
  ('Spite', 'Bracelet of Strengthening'),
  ('Spite', 'Pair of Soulstalkers'),
  ('Spite', 'Pair of Soulwalkers'),
  ('Spite', 'Soulbastion'),
  ('Spite', 'Soulbiter'),
  ('Spite', 'Soulbleeder'),
  ('Spite', 'Soulcrusher'),
  ('Spite', 'Soulcutter'),
  ('Spite', 'Souleater (Axe)'),
  ('Spite', 'Soulhexer'),
  ('Spite', 'Soulmaimer'),
  ('Spite', 'Soulmantle'),
  ('Spite', 'Soulpiercer'),
  ('Spite', 'Soulshanks'),
  ('Spite', 'Soulshell'),
  ('Spite', 'Soulshredder'),
  ('Spite', 'Soulshroud'),
  ('Spite', 'Soulstrider'),
  ('Spite', 'Soultainter'),
  ('Spite', 'Soulgarb'),
  ('Spite', 'Soulsoles'),
  ('Spite', 'Soulkamas'),
  ('Cruelty', 'Spectral Horseshoes'),
  ('Cruelty', 'Spectral Horse Tack'),
  ('Cruelty', 'Spectral Saddle'),
  ('Cruelty', 'The Skull of a Beast'),
  ('Cruelty', 'Bracelet of Strengthening'),
  ('Cruelty', 'Pair of Soulstalkers'),
  ('Cruelty', 'Pair of Soulwalkers'),
  ('Cruelty', 'Soulbastion'),
  ('Cruelty', 'Soulbiter'),
  ('Cruelty', 'Soulbleeder'),
  ('Cruelty', 'Soulcrusher'),
  ('Cruelty', 'Soulcutter'),
  ('Cruelty', 'Souleater (Axe)'),
  ('Cruelty', 'Soulhexer'),
  ('Cruelty', 'Soulmaimer'),
  ('Cruelty', 'Soulmantle'),
  ('Cruelty', 'Soulpiercer'),
  ('Cruelty', 'Soulshanks'),
  ('Cruelty', 'Soulshell'),
  ('Cruelty', 'Soulshredder'),
  ('Cruelty', 'Soulshroud'),
  ('Cruelty', 'Soulstrider'),
  ('Cruelty', 'Soultainter'),
  ('Cruelty', 'Soulgarb'),
  ('Cruelty', 'Soulsoles'),
  ('Cruelty', 'Soulkamas'),
  ('Hatred', 'Spectral Horseshoes'),
  ('Hatred', 'Spectral Horse Tack'),
  ('Hatred', 'Spectral Saddle'),
  ('Hatred', 'The Skull of a Beast'),
  ('Hatred', 'Bracelet of Strengthening'),
  ('Hatred', 'Pair of Soulstalkers'),
  ('Hatred', 'Pair of Soulwalkers'),
  ('Hatred', 'Soulbastion'),
  ('Hatred', 'Soulbiter'),
  ('Hatred', 'Soulbleeder'),
  ('Hatred', 'Soulcrusher'),
  ('Hatred', 'Soulcutter'),
  ('Hatred', 'Souleater (Axe)'),
  ('Hatred', 'Soulhexer'),
  ('Hatred', 'Soulmaimer'),
  ('Hatred', 'Soulmantle'),
  ('Hatred', 'Soulpiercer'),
  ('Hatred', 'Soulshanks'),
  ('Hatred', 'Soulshell'),
  ('Hatred', 'Soulshredder'),
  ('Hatred', 'Soulshroud'),
  ('Hatred', 'Soulstrider'),
  ('Hatred', 'Soultainter'),
  ('Hatred', 'Soulgarb'),
  ('Hatred', 'Soulsoles'),
  ('Hatred', 'Soulkamas'),
  ('Megalomania', 'Spectral Horseshoes'),
  ('Megalomania', 'Spectral Horse Tack'),
  ('Megalomania', 'Spectral Saddle'),
  ('Megalomania', 'The Skull of a Beast'),
  ('Megalomania', 'Bracelet of Strengthening'),
  ('Megalomania', 'Pair of Soulstalkers'),
  ('Megalomania', 'Pair of Soulwalkers'),
  ('Megalomania', 'Soulbastion'),
  ('Megalomania', 'Soulbiter'),
  ('Megalomania', 'Soulbleeder'),
  ('Megalomania', 'Soulcrusher'),
  ('Megalomania', 'Soulcutter'),
  ('Megalomania', 'Souleater (Axe)'),
  ('Megalomania', 'Soulhexer'),
  ('Megalomania', 'Soulmaimer'),
  ('Megalomania', 'Soulmantle'),
  ('Megalomania', 'Soulpiercer'),
  ('Megalomania', 'Soulshanks'),
  ('Megalomania', 'Soulshell'),
  ('Megalomania', 'Soulshredder'),
  ('Megalomania', 'Soulshroud'),
  ('Megalomania', 'Soulstrider'),
  ('Megalomania', 'Soultainter'),
  ('Megalomania', 'Soulgarb'),
  ('Megalomania', 'Soulsoles'),
  ('Megalomania', 'Soulkamas'),
  ('Plunder', 'Alicorn Headguard'),
  ('Plunder', 'Alicorn Quiver'),
  ('Plunder', 'Alicorn Ring'),
  ('Plunder', 'Arboreal Crown'),
  ('Plunder', 'Arboreal Ring'),
  ('Plunder', 'Arboreal Tome'),
  ('Plunder', 'Arcanomancer Folio'),
  ('Plunder', 'Arcanomancer Regalia'),
  ('Plunder', 'Arcanomancer Sigil'),
  ('Plunder', 'Spiritthorn Armor'),
  ('Plunder', 'Spiritthorn Helmet'),
  ('Plunder', 'Spiritthorn Ring'),
  ('Plunder', 'Ethereal Coned Hat'),
  ('Plunder', 'Ethereal Ring'),
  ('Maior Domus', 'Cloud in a Bottle'),
  ('Maior Domus', 'Auric Moon Sigil'),
  ('Maior Domus', 'Moonsilver Battle Visor'),
  ('Maior Domus', 'Moonsilver Nimbus Hat'),
  ('Maior Domus', 'Moonsilver Spirit Mask'),
  ('Maior Domus', 'Moonsilver Strike Helm'),
  ('Maior Domus', 'Moonsilver Trail Hood'),
  ('Mima Haffar', 'Cloud in a Bottle'),
  ('Mima Haffar', 'Auric Moon Sigil'),
  ('Mima Haffar', 'Moonsilver Battle Visor'),
  ('Mima Haffar', 'Moonsilver Nimbus Hat'),
  ('Mima Haffar', 'Moonsilver Spirit Mask'),
  ('Mima Haffar', 'Moonsilver Strike Helm'),
  ('Mima Haffar', 'Moonsilver Trail Hood');
